g:\adb pull /system/lib/libdl.so                            m:\android\system\lib_1.0\libdl.so                
g:\adb pull /system/lib/libc.so                             m:\android\system\lib_1.0\libc.so                 
g:\adb pull /system/lib/libthread_db.so                     m:\android\system\lib_1.0\libthread_db.so         
g:\adb pull /system/lib/libm.so                             m:\android\system\lib_1.0\libm.so                 
g:\adb pull /system/lib/libstdc++.so                        m:\android\system\lib_1.0\libstdc++.so            
g:\adb pull /system/lib/liblog.so                           m:\android\system\lib_1.0\liblog.so               
g:\adb pull /system/lib/libz.so                             m:\android\system\lib_1.0\libz.so                 
g:\adb pull /system/lib/libcrypto.so                        m:\android\system\lib_1.0\libcrypto.so            
g:\adb pull /system/lib/libexpat.so                         m:\android\system\lib_1.0\libexpat.so             
g:\adb pull /system/lib/libicudata.so                       m:\android\system\lib_1.0\libicudata.so           
g:\adb pull /system/lib/libdbus.so                          m:\android\system\lib_1.0\libdbus.so              
g:\adb pull /system/lib/libbluetooth.so                     m:\android\system\lib_1.0\libbluetooth.so         
g:\adb pull /system/lib/libvorbisidec.so                    m:\android\system\lib_1.0\libvorbisidec.so        
g:\adb pull /system/lib/libaes.so                           m:\android\system\lib_1.0\libaes.so               
g:\adb pull /system/lib/libctest.so                         m:\android\system\lib_1.0\libctest.so             
g:\adb pull /system/lib/libcutils.so                        m:\android\system\lib_1.0\libcutils.so            
g:\adb pull /system/lib/libssl.so                           m:\android\system\lib_1.0\libssl.so               
g:\adb pull /system/lib/libicuuc.so                         m:\android\system\lib_1.0\libicuuc.so             
g:\adb pull /system/lib/libnetutils.so                      m:\android\system\lib_1.0\libnetutils.so          
g:\adb pull /system/lib/libwpa_client.so                    m:\android\system\lib_1.0\libwpa_client.so        
g:\adb pull /system/lib/libutils.so                         m:\android\system\lib_1.0\libutils.so             
g:\adb pull /system/lib/libicui18n.so                       m:\android\system\lib_1.0\libicui18n.so           
g:\adb pull /system/lib/libcorecg.so                        m:\android\system\lib_1.0\libcorecg.so            
g:\adb pull /system/lib/libhardware.so                      m:\android\system\lib_1.0\libhardware.so          
g:\adb pull /system/lib/libsonivox.so                       m:\android\system\lib_1.0\libsonivox.so           
g:\adb pull /system/lib/libdrm1.so                          m:\android\system\lib_1.0\libdrm1.so              
g:\adb pull /system/lib/libril.so                           m:\android\system\lib_1.0\libril.so               
g:\adb pull /system/lib/libsqlite.so                        m:\android\system\lib_1.0\libsqlite.so            
g:\adb pull /system/lib/libdrm1_jni.so                      m:\android\system\lib_1.0\libdrm1_jni.so          
g:\adb pull /system/lib/libreference-ril.so                 m:\android\system\lib_1.0\libreference-ril.so     
g:\adb pull /system/lib/libpixelflinger.so                  m:\android\system\lib_1.0\libpixelflinger.so      
g:\adb pull /system/lib/libagl.so                           m:\android\system\lib_1.0\libagl.so               
g:\adb pull /system/lib/libnativehelper.so                  m:\android\system\lib_1.0\libnativehelper.so      
g:\adb pull /system/lib/libui.so                            m:\android\system\lib_1.0\libui.so                
g:\adb pull /system/lib/libexif.so                          m:\android\system\lib_1.0\libexif.so              
g:\adb pull /system/lib/libcameraservice.so                 m:\android\system\lib_1.0\libcameraservice.so     
g:\adb pull /system/lib/libmedia.so                         m:\android\system\lib_1.0\libmedia.so             
g:\adb pull /system/lib/libGLES_CM.so                       m:\android\system\lib_1.0\libGLES_CM.so           
g:\adb pull /system/lib/libaudioflinger.so                  m:\android\system\lib_1.0\libaudioflinger.so      
g:\adb pull /system/lib/libdvm.so                           m:\android\system\lib_1.0\libdvm.so               
g:\adb pull /system/lib/libUAPI_jni.so                      m:\android\system\lib_1.0\libUAPI_jni.so          
g:\adb pull /system/lib/libsgl.so                           m:\android\system\lib_1.0\libsgl.so               
g:\adb pull /system/lib/libsurfaceflinger.so                m:\android\system\lib_1.0\libsurfaceflinger.so    
g:\adb pull /system/lib/libandroid_runtime.so               m:\android\system\lib_1.0\libandroid_runtime.so   
g:\adb pull /system/lib/libsoundpool.so                     m:\android\system\lib_1.0\libsoundpool.so         
g:\adb pull /system/lib/libFFTEm.so                         m:\android\system\lib_1.0\libFFTEm.so             
g:\adb pull /system/lib/libpvcommon.so                      m:\android\system\lib_1.0\libpvcommon.so          
g:\adb pull /system/lib/libpvauthor.so                      m:\android\system\lib_1.0\libpvauthor.so          
g:\adb pull /system/lib/libpvplayer.so                      m:\android\system\lib_1.0\libpvplayer.so          
g:\adb pull /system/lib/libpvdownloadreg.so                 m:\android\system\lib_1.0\libpvdownloadreg.so     
g:\adb pull /system/lib/libpvrtspreg.so                     m:\android\system\lib_1.0\libpvrtspreg.so         
g:\adb pull /system/lib/libmediaplayerservice.so            m:\android\system\lib_1.0\libmediaplayerservice.so
g:\adb pull /system/lib/libmedia_jni.so                     m:\android\system\lib_1.0\libmedia_jni.so         
g:\adb pull /system/lib/libpvmp4reg.so                      m:\android\system\lib_1.0\libpvmp4reg.so          
g:\adb pull /system/lib/libsystem_server.so                 m:\android\system\lib_1.0\libsystem_server.so     
g:\adb pull /system/lib/libandroid_servers.so               m:\android\system\lib_1.0\libandroid_servers.so   
g:\adb pull /system/lib/libpvmp4.so                         m:\android\system\lib_1.0\libpvmp4.so             
g:\adb pull /system/lib/libpvnet_support.so                 m:\android\system\lib_1.0\libpvnet_support.so     
g:\adb pull /system/lib/libpvdownload.so                    m:\android\system\lib_1.0\libpvdownload.so        
g:\adb pull /system/lib/libpvrtsp.so                        m:\android\system\lib_1.0\libpvrtsp.so            
g:\adb pull /system/lib/libwebcore.so											 m:\android\system\lib_1.0\libwebcore.so
