/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.msi.manning.UnlockingAndroid;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int android=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int closejob=0x7f05000b;
        public static final int details=0x7f050008;
        public static final int emailaddress=0x7f05000c;
        public static final int emailaddresslabel=0x7f050000;
        public static final int getjobs=0x7f050001;
        public static final int joblist=0x7f050006;
        public static final int joblistview=0x7f050004;
        public static final int mapjob=0x7f050009;
        public static final int productinfo=0x7f05000a;
        public static final int serverurl=0x7f05000d;
        public static final int settings=0x7f050003;
        public static final int settingssave=0x7f05000e;
        public static final int showjob=0x7f050007;
        public static final int showjobs=0x7f050002;
        public static final int statuslabel=0x7f050005;
    }
    public static final class layout {
        public static final int fieldservice=0x7f030000;
        public static final int managejobs=0x7f030001;
        public static final int refreshjobs=0x7f030002;
        public static final int showjob=0x7f030003;
        public static final int showsettings=0x7f030004;
        public static final int splash=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
}
